In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split


In [2]:
data = pd.read_csv("letter-recognition.data", header=None)
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,D,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19996,C,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19997,T,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19998,S,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8


In [3]:
# Split features and labels
X = data.iloc[:, 1:].values   # 16 features
y = data.iloc[:, 0].values    # letters
print(X)
print(y)

[[ 2  8  3 ...  8  0  8]
 [ 5 12  3 ...  8  4 10]
 [ 4 11  6 ...  7  3  9]
 ...
 [ 6  9  6 ... 12  2  4]
 [ 2  3  4 ...  9  5  8]
 [ 4  9  6 ...  7  2  8]]
['T' 'I' 'D' ... 'T' 'S' 'A']


In [4]:
# Encode labels
le = LabelEncoder()
y = le.fit_transform(y)

# Normalize features
scaler = StandardScaler()
X = scaler.fit_transform(X)
X

array([[-1.0576983 ,  0.29187713, -1.05327668, ..., -0.21908163,
        -1.4381527 ,  0.12291107],
       [ 0.51038497,  1.5023577 , -1.05327668, ..., -0.21908163,
         0.12008142,  1.35944092],
       [-0.01230945,  1.19973756,  0.43590966, ..., -0.8656262 ,
        -0.26947711,  0.74117599],
       ...,
       [ 1.03307939,  0.59449727,  0.43590966, ...,  2.36709667,
        -0.65903564, -2.35014863],
       [-1.0576983 , -1.22122359, -0.55688123, ...,  0.42746295,
         0.50963994,  0.12291107],
       [-0.01230945,  0.59449727,  0.43590966, ..., -0.8656262 ,
        -0.65903564,  0.12291107]])

In [5]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [6]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [7]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(16,)),
    Dense(64, activation='relu'),
    Dense(26, activation='softmax')   # 26 classes
])

C:\Users\Varad\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [20]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [9]:
history = model.fit(
    X_train, y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.1
)

Epoch 1/30
450/450 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.5518 - loss: 1.6609 - val_accuracy: 0.7225 - val_loss: 0.9670
Epoch 2/30
450/450 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7684 - loss: 0.8001 - val_accuracy: 0.8044 - val_loss: 0.6851
Epoch 3/30
450/450 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8244 - loss: 0.6059 - val_accuracy: 0.8375 - val_loss: 0.5489
Epoch 4/30
450/450 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8535 - loss: 0.4986 - val_accuracy: 0.8625 - val_loss: 0.4702
Epoch 5/30
450/450 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8722 - loss: 0.4260 - val_accuracy: 0.8813 - val_loss: 0.4110
Epoch 6/30
450/450 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8896 - loss: 0.3730 - val_accuracy: 0.8894 - val_loss: 0.3713
Epoch 7/30
450/450 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9000 - loss: 0.3340 - val_accuracy: 0.8994 - val_loss: 0.3376
Epoch 8/30
450/450 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9072 - loss: 0.3014 - val_accuracy: 0.

In [10]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9475 - loss: 0.1701
Test Accuracy: 0.9474999904632568


In [11]:
import numpy as np

sample = X_test[0].reshape(1, -1)
prediction = model.predict(sample)

predicted_letter = le.inverse_transform([np.argmax(prediction)])
print("Predicted:", predicted_letter)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 238ms/step
Predicted: ['T']
